<?php

namespace BibliothequeUniversitaire\EntiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AuteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuteurRepository extends EntityRepository
{
    public function findAll()
    {
        return $this->findBy(array(), array('prenom' => 'ASC', 'nom' => 'ASC'));
    }
}
