<?php

namespace BibliothequeUniversitaire\EntiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ThemeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ThemeRepository extends EntityRepository
{
    public function findAll()
    {
        return $this->findBy(array(), array('libelle' => 'ASC'));
    }

    public function findAlltoArray()
    {
        $queryBuilder = $this->createQueryBuilder('t');
        $queryBuilder
            ->select('t.id', 't.libelle')
            ->orderBy('t.libelle', 'ASC');

        $themes = $queryBuilder->getQuery()->getArrayResult();

        foreach ($themes as $theme)
        {
            $key = $theme['id'];
            $listeThemes[$key] = $theme['libelle'];
        }

        return $listeThemes;
    }
}
