BibliothequeUniversitaire\EntiteBundle\Entity\Cycle:
    type: entity
    table: null
    repositoryClass: BibliothequeUniversitaire\EntiteBundle\Entity\CycleRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        libelle:
            type: string
            length: '10'
        nombreLivres:
            type: integer
            column: nombre_livres
        duree:
            type: integer
    lifecycleCallbacks: {  }
