BibliothequeUniversitaire\EntiteBundle\Entity\Emprunt:
    type: entity
    table: null
    repositoryClass: BibliothequeUniversitaire\EntiteBundle\Entity\EmpruntRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        dateDebut:
            type: date
            column: date_debut
    oneToOne:
        exemplaire_emprunte:
            targetEntity: Exemplaire
    manyToOne:
        lecteur_emprunteur:
            targetEntity: Lecteur